apiVersion: batch/v1
kind: Job
metadata:
  name: cucumber-tests
spec:
  template:
    spec:
      containers:
        - name: cucumber
          image: IMAGE_PLACEHOLDER
          env:
            - name: CUCUMBER_TAGS
              value: "@regression"
          command: ["mvn", "test", "-Dcucumber.filter.tags=$(CUCUMBER_TAGS)"]
          volumeMounts:
            - name: reports-storage
              mountPath: /app/target/cucumber-reports
      restartPolicy: Never
      volumes:
        - name: reports-storage
          persistentVolumeClaim:
            claimName: reports-pvc
  backoffLimit: 0

