apiVersion: batch/v1
kind: Job
metadata:
  name: cucumber-tests
spec:
  template:
    spec:
      containers:
        - name: cucumber
          image: IMAGE_PLACEHOLDER
          env:
            - name: CUCUMBER_TAGS
              value: "@regression"
          command: ["mvn", "test", "-Dcucumber.filter.tags=$(CUCUMBER_TAGS)"]
      restartPolicy: Never
  backoffLimit: 0

