name: CI - Run Cucumber tests in k3d

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d cluster
        run: k3d cluster create ci-cluster --wait

      - name: Build Docker image
        run: |
          IMAGE=ci-cucumber:${{ github.sha }}
          docker build -t $IMAGE .
          k3d image import $IMAGE -c ci-cluster
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy Cucumber job
        run: |
          sed "s|IMAGE_PLACEHOLDER|$IMAGE|" k8s/job-temp.yml > job.yml
          kubectl apply -f job.yml

      - name: Wait for job completion
        run: |
          kubectl wait --for=condition=complete --timeout=300s job/cucumber-tests

      - name: Get pod logs
        run: |
          POD=$(kubectl get pods -l job-name=cucumber-tests -o jsonpath='{.items[0].metadata.name}')
          echo "Pod name: $POD"
          kubectl logs $POD

      - name: List contents of target directory
        run: |
         POD=$(kubectl get pods -l job-name=cucumber-tests -o jsonpath='{.items[0].metadata.name}')
         echo "Inspecting /app/target in pod: $POD"
         kubectl exec $POD -- ls -R /app/target || echo "⚠️ /app/target not found"


      - name: Copy reports
        run: |
         POD=$(kubectl get pods -l job-name=cucumber-tests -o jsonpath='{.items[0].metadata.name}')
         echo "Copying reports from pod: $POD"
         mkdir -p ./reports
         kubectl cp $POD:/app/target/cucumber-reports ./reports/cucumber-reports || echo "⚠️ cucumber-reports not found"
         kubectl cp $POD:/app/target/surefire-reports ./reports/surefire-reports || echo "⚠️ surefire-reports not found"

 
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: ./reports


